INSERT INTO `specialty` (name) VALUES 
('Allergy and immunology'),
('Adolescent medicine'),
('Anesthesiology'),
('Cardiology'),
('Cardiothoracic surgery'),
('Child and adolescent psychiatry'),
('Clinical neurophysiology'),
('Dermatology'),
('Emergency medicine'),
('Endocrinology'),
('Family Medicine'),
('Forensic pathology'),
('Forensic psychiatry'),
('Gastroenterology'),
('General surgery'),
('Hematology'),
('Infectious disease'),
('Intensive care medicine'),
('Nephrology'),
('Neurology'),
('Neuropathology'),
('Neurosurgery'),
('Obstetrics and gynecology'),
('Ophthalmology'),
('Orthopedic surgery'),
('Oral and maxillofacial surgery'),
('Otorhinolaryngology'),
('Pathology'),
('Pediatrics'),
('Pediatric allergy and immunology'),
('Pediatric cardiology'),
('Pediatric emergency medicine'),
('Pediatric endocrinology'),
('Pediatric gastroenterology'),
('Pediatric hematology and oncology'),
('Pediatric infectious disease'),
('Pediatric nephrology'),
('Pediatric respiratory medicine'),
('Pediatric rheumatology'),
('Pediatric surgery'),
('Physical medicine and rehabilitation'),
('Plastic, reconstructive and aesthetic surgery'),
('Psychiatry'),
('Radiation oncology'),
('Radiology'),
('Reproductive endocrinology and infertility'),
('Respiratory medicine'),
('Rheumatology'),
('Sports medicine'),
('Thoracic surgery'),
('Neuroradiology'),
('Urology'),
('Urology');
